### ISSUE TITLE
Not supported by Galaxy with Python `3`

### ISSUE THREAD

**Issue by xtrojak** [ISA-tools/mzml2isa-galaxy#10]
This wrapper is no longer supported by Galaxy, which runs with Python `3`. This [line](https://github.com/ISA-tools/mzml2isa-galaxy/blob/476d6f78e24892d29436e2fb48c1094a7e1b4719/galaxy/mzml2isa/ontology_search.py#L19) definitely produces syntax error in Python `3`, but there might be more issues.

```
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Table not recognised")?
```

**Comment by Tomnl** [comment]
Thanks @xtrojak - let me have a look at this. I haven't visited this for a while and there have been a few mzml2isa updates since the wrapper was last updated

**Comment by Tomnl** [comment]
Hi @xtrojak - I have updated the Galaxy wrapper (https://github.com/ISA-tools/mzml2isa-galaxy/pull/11) and updated the Galaxy toolshed.

Let me know if you have any issues

**Comment by Tomnl** [comment]
I think I can safely close this issue now. Thanks for raising the issue @xtrojak

**Comment by xtrojak** [comment]
Agreed, thank you for prompt solution of the issue!
